language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "git clone https://github.com/pydata/pandas.git && cd pandas && python setup.py develop && cd .."  # Temporary until v0.14 release
  - "pip install coverage"
  - "pip install ."

# command to run tests
script:
  - nosetests --with-cover --cover-package=query
