language: python
python:
  - "2.7"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install nose coverage mysql-python ipython"  # Extras needed for testing
  - "pip install ."

# command to run tests
script:
  - nosetests --with-cover --cover-package=query
